CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock_count INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

INSERT INTO products (name, stock_count)
VALUES
    ('T-Shirt - Small', 50),
    ('Jeans - Blue', 25),
    ('Sneakers - Black', 12);
