CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    last_updated TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT products_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT products_stock_count_non_negative CHECK (stock_count >= 0),
    CONSTRAINT products_name_unique UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_products_name ON products (name);
CREATE INDEX IF NOT EXISTS idx_products_stock_count ON products (stock_count);

COMMENT ON TABLE products IS 'Master data inventory products for the dashboard MVP.';
COMMENT ON COLUMN products.name IS 'Display name of the product item.';
COMMENT ON COLUMN products.stock_count IS 'Current available stock quantity.';
COMMENT ON COLUMN products.created_at IS 'UTC timestamp when the product row was created.';
COMMENT ON COLUMN products.last_updated IS 'UTC timestamp automatically refreshed on every update.';

CREATE OR REPLACE FUNCTION set_products_last_updated()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_updated = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_last_updated ON products;
CREATE TRIGGER trg_products_last_updated
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_products_last_updated();

INSERT INTO products (name, stock_count)
VALUES
    ('T-Shirt - Small', 50),
    ('Jeans - Blue', 25),
    ('Sneakers - Black', 12)
ON CONFLICT (name) DO UPDATE
SET
    stock_count = EXCLUDED.stock_count,
    last_updated = timezone('utc'::text, now());
